openapi: 3.0.3
info:
  title: Task Manager API
  description: API para la gestión de tareas del curso Diseño de APIs REST
  version: 1.0.0
  contact:
    name: Equipo del curso
    email: soporte@taskmanager.dev
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://localhost:3000/v1
    description: Servidor local de desarrollo
  - url: https://staging.api.taskmanager.dev/v1
    description: Servidor local de staging
tags:
  - name: Tasks
    description: Operaciones relacionadas con la gestión de tareas
paths:
  /tasks:
    get:
      # This API has no security
      security: []
      tags:
        - Tasks
      summary: Obtener todas las tareas
      description: Devuelve una lista de tareas registradas
      operationId: getAllTasks
      responses:
        '200':
          description: Lista de tareas obtenida correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        '400':
          description: Ha ocurrido algún error durante la ejecución
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      # This API has no security
      security: []
      tags:
        - Tasks
      summary: Crear una nueva tarea
      description: Crea una nueva tarea a partir de los datos enviados
      operationId: createTask
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
              
      responses:
        '201':
          description: Tarea creada correctamente. Devuelve el ID de la tarea que se acaba de crear
        '400':
          description: Ha ocurrido algún error durante la ejecución
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas: 
    Task:
      type: object
      required:
        - title
        - status
      properties:
        id:
          type: string
          example: "64ab32cd9f0c1e12a45b78d9"
        title:
          type: string
          example: "Preparar práctica de OpenAPI"
        description:
          type: string
          example: "Definir modelos y esquemas en OpenAPI"
        status:
          type: string
          enum: [todo, in_progress, done]
          example: "todo"
        priority:
          type: string
          enum: [low, medium, high]
          example: "medium"
        dueDate:
          type: string
          format: date-time
          example: "2025-10-30T14:00:00Z"
        tags:
          type: array
          items:
            type: string
            example: [home, work]
    Error:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          example: "Validation error"
        details:
          type: string
          example: "The field 'title' is required"