openapi: 3.0.3
info:
  title: Task Manager API – Curso API First
  description: API de referencia para el curso (definición OpenAPI + implementación Express).
  version: 1.0.0
  contact:
    name: Equipo del curso
    email: soporte@taskmanager.dev
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://localhost:3000/v1
    description: Servidor local de desarrollo
  - url: https://staging.api.taskmanager.dev/v1
    description: Servidor local de staging
tags:
  - name: Tasks
    description: Operaciones relacionadas con la gestión de tareas
paths:
  /tasks:
    get:
      # This API has no security
      security: []
      tags:
        - Tasks
      summary: Obtener todas las tareas
      description: Devuelve una lista de tareas registradas
      operationId: getAllTasks
      responses:
        '200':
          description: Lista paginada de tareas
          content:
            application/json:
              schema:
                type: object
                required: [items, page, limit, totalItems]
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Task'
                  page:
                    type: integer
                    example: 1
                  limit:
                    type: integer
                    example: 10
                  totalItems:
                    type: integer
                    example: 42
                  totalPages:
                    type: integer
                    example: 5
        '400':
          $ref: '#/components/responses/ErrorResponse'
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
            minimum: 1
          description: Página de resultados
        - in: query
          name: limit
          schema:
            type: integer
            default: 10
            minimum: 1
            maximum: 100
          description: Número de resultados por página
        - in: query
          name: status
          schema:
            type: string
            enum: [todo, in_progress, done]
          description: Filtrar por estado
        - in: query
          name: priority
          schema:
            type: string
            enum: [low, medium, high]
          description: Filtrar por prioridad
        - in: query
          name: search
          schema:
            type: string
          description: Buscar texto en el título
    post:
      # This API has no security
      security: []
      tags:
        - Tasks
      summary: Crear una nueva tarea
      description: Crea una nueva tarea a partir de los datos enviados
      operationId: createTask
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
            example:
              title: "Revisar errores"
              status: "todo"
              
      responses:
        '201':
          description: Tarea creada correctamente. Devuelve el ID de la tarea que se acaba de crear
          content:
            application/json:              
              examples:
                ejemplo:
                  value:
                    id: "2"
                    title: "Nueva tarea desde mock"
                    status: "todo"
                    createdAt: "2025-10-30T10:00:00Z" 
        '400':
          $ref: '#/components/responses/ErrorResponse'
components:
  schemas: 
    Task:
      type: object
      required:
        - title
        - status
      properties:
        id:
          type: string
          example: "64ab32cd9f0c1e12a45b78d9"
        title:
          type: string
          example: "Preparar práctica de OpenAPI"
        description:
          type: string
          example: "Definir modelos y esquemas en OpenAPI"
        status:
          type: string
          enum: [todo, in_progress, done]
          example: "todo"
        priority:
          type: string
          enum: [low, medium, high]
          example: "medium"
        dueDate:
          type: string
          format: date-time
          example: "2025-10-30T14:00:00Z"
        createdAt:
          type: string
          format: date-time
          example: "2025-10-30T14:00:00Z"
        tags:
          type: array
          items:
            type: string
            example: [home, work]
    Error:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          example: "Validation error"
        details:
          type: string
          example: "The field 'title' is required"
    ProblemDetails:
      type: object
      properties:
        type:
          type: string
          example: "https://api.ejemplo.com/errors/validation"
        title:
          type: string
          example: "Validation error"
        status:
          type: integer
          example: 400
        detail:
          type: string
          example: "Missing field 'title'"
        instance:
          type: string
          example: "/tasks"
  responses:
    ErrorResponse:
      description: Error genérico
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  